language: generic
matrix:
  include:
  - language: python
    name: "ui-server"
    python: 3.6
    sudo: false
    cache: pip
    before_install:
    - cd ui-server
    install:
    - pip install -r requirements.txt
    script:
    - pylint src/

  - language: node_js
    name: "client-ui"
    node_js: 8
    sudo: false
    branches:
      except:
      - gh-pages
    cache:
      directories:
      - "$HOME/.npm"
    before_install:
    - cd ui
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    install:
    - npm ci
    script:
    - ng test --watch=false
    - ng build --prod --base-href=/northernpike/
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      on:
        branch: master
      local_dir: ui/dist/controlpanel
