# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: telemetry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='telemetry.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0ftelemetry.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n\x05\x41lert\x12\x12\n\nalert_text\x18\x01 \x01(\t\"\x95\x01\n\x06Switch\x12\x30\n\x0cmessage_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x1d\n\x06states\x18\x03 \x03(\x0b\x32\r.Switch.State\x1a+\n\x05State\x12\x13\n\x0bswitch_name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08\"\xd0\x01\n\x07\x43ontrol\x12\x30\n\x0cmessage_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12!\n\x04\x61xes\x18\x02 \x03(\x0b\x32\x13.Control.AnalogAxis\x1ap\n\nAnalogAxis\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nx_position\x18\x02 \x01(\x02\x12\x12\n\ny_position\x18\x03 \x01(\x02\x12\x15\n\rangle_degrees\x18\x04 \x01(\x05\x12\x15\n\rangle_radians\x18\x05 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ALERT = _descriptor.Descriptor(
  name='Alert',
  full_name='Alert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alert_text', full_name='Alert.alert_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=79,
)


_SWITCH_STATE = _descriptor.Descriptor(
  name='State',
  full_name='Switch.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='switch_name', full_name='Switch.State.switch_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='Switch.State.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=231,
)

_SWITCH = _descriptor.Descriptor(
  name='Switch',
  full_name='Switch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_time', full_name='Switch.message_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='count', full_name='Switch.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='states', full_name='Switch.states', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SWITCH_STATE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=231,
)


_CONTROL_ANALOGAXIS = _descriptor.Descriptor(
  name='AnalogAxis',
  full_name='Control.AnalogAxis',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Control.AnalogAxis.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x_position', full_name='Control.AnalogAxis.x_position', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_position', full_name='Control.AnalogAxis.y_position', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angle_degrees', full_name='Control.AnalogAxis.angle_degrees', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='angle_radians', full_name='Control.AnalogAxis.angle_radians', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=442,
)

_CONTROL = _descriptor.Descriptor(
  name='Control',
  full_name='Control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_time', full_name='Control.message_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='axes', full_name='Control.axes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CONTROL_ANALOGAXIS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=442,
)

_SWITCH_STATE.containing_type = _SWITCH
_SWITCH.fields_by_name['message_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SWITCH.fields_by_name['states'].message_type = _SWITCH_STATE
_CONTROL_ANALOGAXIS.containing_type = _CONTROL
_CONTROL.fields_by_name['message_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CONTROL.fields_by_name['axes'].message_type = _CONTROL_ANALOGAXIS
DESCRIPTOR.message_types_by_name['Alert'] = _ALERT
DESCRIPTOR.message_types_by_name['Switch'] = _SWITCH
DESCRIPTOR.message_types_by_name['Control'] = _CONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Alert = _reflection.GeneratedProtocolMessageType('Alert', (_message.Message,), dict(
  DESCRIPTOR = _ALERT,
  __module__ = 'telemetry_pb2'
  # @@protoc_insertion_point(class_scope:Alert)
  ))
_sym_db.RegisterMessage(Alert)

Switch = _reflection.GeneratedProtocolMessageType('Switch', (_message.Message,), dict(

  State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), dict(
    DESCRIPTOR = _SWITCH_STATE,
    __module__ = 'telemetry_pb2'
    # @@protoc_insertion_point(class_scope:Switch.State)
    ))
  ,
  DESCRIPTOR = _SWITCH,
  __module__ = 'telemetry_pb2'
  # @@protoc_insertion_point(class_scope:Switch)
  ))
_sym_db.RegisterMessage(Switch)
_sym_db.RegisterMessage(Switch.State)

Control = _reflection.GeneratedProtocolMessageType('Control', (_message.Message,), dict(

  AnalogAxis = _reflection.GeneratedProtocolMessageType('AnalogAxis', (_message.Message,), dict(
    DESCRIPTOR = _CONTROL_ANALOGAXIS,
    __module__ = 'telemetry_pb2'
    # @@protoc_insertion_point(class_scope:Control.AnalogAxis)
    ))
  ,
  DESCRIPTOR = _CONTROL,
  __module__ = 'telemetry_pb2'
  # @@protoc_insertion_point(class_scope:Control)
  ))
_sym_db.RegisterMessage(Control)
_sym_db.RegisterMessage(Control.AnalogAxis)


# @@protoc_insertion_point(module_scope)
